### ISSUE TITLE
Web reporter showing NaN errors when iterations >1

### ISSUE THREAD

**Issue by juannavalonribas** [bamlab/android-performance-profiler#65]
Hello 👋🏻 , 

### Problem
So I have a weird behaviour using the library, sometimes everything works perfectly and sometimes it doesn't. Please check the following [image](https://imgur.com/a/d5wSOYY) in order to see the NaN error.

_This error only appears when Im running more than 1 iteration_

[Here's](https://gist.github.com/juannavalonribas/abb50fa979646797a06782016575be86) the json of the failed

I just launched 3 times the test with different iterations:

- First launch = 1 iteration
- Second launch = 2 iterations
- Third launch = 4 iterations

### Code test example
I am running this simple test using appium(2.0.0-beta.47) with javascript.

```
describe(`Performance in ${country.countryCode}`, () => {
  beforeEach(async () => {
    await checkAppStatus();
  });
  it('Just Click in login button', async () => {
    await HomeScreen.goToLogin();
    await new Promise(resolve => setTimeout(resolve, 5000));
  });
});
```

### Scenario
Running on a MacBook Pro 13-inch, M1, 2020 | macOS: Ventura 13.0.1
Launched using a real device connected via USB - Xiaomi Redmi Note 9 S

**Comment by Almouro** [comment]
Hi @juannavalonribas, 

Thanks for the details! When I check the [Json file](https://gist.github.com/juannavalonribas/abb50fa979646797a06782016575be86) you posted, I get 46/100 score exactly like you result with 1 iteration.
Is it the right JSON file?

But another issue is that there is still only 500ms of measures instead of 13s
That seems similar to this issue you posted https://github.com/bamlab/android-performance-profiler/issues/63#issuecomment-1358010834, so it seems like even for 1 iteration it's not working properly, which is really weird 🤔

**Comment by juannavalonribas** [comment]
Hello @Almouro sorry for my late response. I am going to check again all the data and I'll give you an update.

Thanks!

**Comment by Almouro** [comment]
@juannavalonribas no worries of course! (Plus, I was the one who took 2 weeks to answer in the first place 😅)

**Comment by juannavalonribas** [comment]
Hello @Almouro,

After the refactor of our entire project I am not able to reproduce the error in our new container. I do not know the reason with the NaN values but after execute some tests everything is working fine. 

Thanks!

**Comment by Almouro** [comment]
Hi @juannavalonribas, glad to hear it! 🥳 
Don't hesitate to post again in case there's any issue
